name: Automated E2E Testing
on: 
  pull_request:
  workflow_dispatch:
env:
    email: cesuntest@stud.noroff.no
    username: cesun
    password: cesuntest
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
